require_relative '../../node_modules/@capacitor/ios/scripts/pods_helpers'

platform :ios, '14.0'
use_frameworks!

# workaround to avoid Xcode caching of Pods that requires
# Product -> Clean Build Folder after new Cordova plugins installed
# Requires CocoaPods 1.6 or newer
install! 'cocoapods', :disable_input_output_paths => true

def capacitor_pods
  pod 'Capacitor', :path => '../../node_modules/@capacitor/ios'
  pod 'CapacitorCordova', :path => '../../node_modules/@capacitor/ios'
  pod 'CapacitorCommunityAppleSignIn', :path => '../../node_modules/@capacitor-community/apple-sign-in'
  pod 'CapacitorFirebaseAuthentication', :path => '../../node_modules/@capacitor-firebase/authentication'
  pod 'CapacitorFirebaseMessaging', :path => '../../node_modules/@capacitor-firebase/messaging'
  pod 'CapacitorApp', :path => '../../node_modules/@capacitor/app'
  pod 'CapacitorLocalNotifications', :path => '../../node_modules/@capacitor/local-notifications'
  pod 'RevenuecatPurchasesCapacitor', :path => '../../node_modules/@revenuecat/purchases-capacitor'
end

target 'App' do
  capacitor_pods
  # Add your Pods here
end

# Must match App + ProyouWidgetExtension targets in App.xcodeproj (Signing & Capabilities).
PROYOU_DEVELOPMENT_TEAM = ENV.fetch('PROYOU_DEVELOPMENT_TEAM', 'HF3AKH98PY')

post_install do |installer|
  assertDeploymentTarget(installer)
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['DEVELOPMENT_TEAM'] = PROYOU_DEVELOPMENT_TEAM
      config.build_settings['CODE_SIGN_STYLE'] = 'Automatic'
    end
  end
  # Xcode 15+: silence "will be run during every build" on [CP] scripts when
  # disable_input_output_paths is enabled (Capacitor recommendation).
  installer.aggregate_targets.each do |aggregate_target|
    aggregate_target.user_project.native_targets.each do |target|
      target.shell_script_build_phases.each do |phase|
        next unless phase.name&.start_with?('[CP]')
        phase.always_out_of_date = '1'
      end
    end
  end
end
